language: scala
scala:
  - "2.13.0-M2"
  - "2.12.3"
  - "2.11.11"
  - "2.10.6"
jdk:
  - oraclejdk8
sudo: false
matrix:
  include:
  - dist: trusty
    group: edge
    sudo: required
    scala: 2.12.3
    jdk: oraclejdk9
    before_install:
    # https://github.com/sbt/sbt/pull/2951
    - git clone https://github.com/retronym/java9-rt-export
    - cd java9-rt-export/
    - git checkout 1019a2873d057dd7214f4135e84283695728395d
    - jdk_switcher use oraclejdk8
    - echo "sbt.version=1.0.0" > project/build.properties
    - sbt package
    - java -version
    - mkdir -p $HOME/.sbt/0.13/java9-rt-ext; java -jar target/java9-rt-export-*.jar $HOME/.sbt/0.13/java9-rt-ext/rt.jar
    - jar tf $HOME/.sbt/0.13/java9-rt-ext/rt.jar | grep java/lang/Object
    - cd ..
    - wget https://raw.githubusercontent.com/paulp/sbt-extras/9ade5fa54914ca8aded44105bf4b9a60966f3ccd/sbt && chmod +x ./sbt
    script:
    - ./sbt -Dscala.ext.dirs=$HOME/.sbt/0.13/java9-rt-ext ++$TRAVIS_SCALA_VERSION test
